# Generated by Django 2.0 on 2018-01-21 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('H', 'Home'), ('W', 'Work'), ('SC', 'School'), ('SH', 'Shopping'), ('M', 'Maintenance'), ('R', 'Recreational'), ('PD', 'Pickup/DropOff')], max_length=2, verbose_name='Purpose of activity')),
                ('day_of_week', models.CharField(choices=[('WD', 'Weekday'), ('WE', 'Weekend')], max_length=2, verbose_name='Activity occurs in weekday or weekend')),
                ('from_id', models.BigIntegerField(verbose_name='ID of from location')),
                ('to_id', models.BigIntegerField(verbose_name='ID of to location')),
                ('from_lat', models.FloatField(verbose_name='Start latitude')),
                ('from_lon', models.FloatField(verbose_name='Start longitude')),
                ('to_lat', models.FloatField(verbose_name='End latitude')),
                ('to_lon', models.FloatField(verbose_name='End longitude')),
                ('probabilities', models.TextField(verbose_name='JSON format of probability values for 96 15-minute time slots')),
            ],
        ),
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('DR', 'Driving'), ('PT', 'Public Transit'), ('WK', 'Walking'), ('BK', 'Biking'), ('UX', 'UberX'), ('UP', 'UberPool')], max_length=2)),
                ('wait_time', models.PositiveSmallIntegerField(default=0)),
                ('travel_time', models.PositiveSmallIntegerField()),
                ('cost', models.CharField(default='', max_length=10)),
                ('slot_id', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(96, 'slot_id must be in the range of 0 - 96')], verbose_name='ID of time slot this option corresponds to')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.Activity')),
            ],
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['id'], name='activity_id_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['from_id', 'to_id'], name='from_to_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('from_id', 'to_id')},
        ),
    ]
