# Generated by Django 2.0 on 2018-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_options', '0002_auto_20180123_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='from_id',
            field=models.BigIntegerField(verbose_name='ID of from location'),
        ),
    ]
